### ISSUE TITLE
Chatroom skeleton function

### ISSUE THREAD

**Issue by yoniaibi** [asoltd/guilds#19]

**Comment by piotrostr** [comment]
Hey @yoniaibi, 

just wanted to remind you that during the issue creation you need to add assignees:

![image](https://user-images.githubusercontent.com/63755291/189338725-bf91572b-f668-4a16-ad0c-3b4384f542cf.png)

and labels:

![image](https://user-images.githubusercontent.com/63755291/189339034-225a7226-0615-4fbb-ad43-6f637bba947e.png)

Otherwise it will get tangled up as the project scales!

Also, be sure to specify whether the issue revolves around:

* feat: (new feature for the user, not a new feature for build script)
* fix: (bug fix for the user, not a fix to a build script)
* docs: (changes to the documentation)
* style: (formatting, missing semi colons, etc; no production code change)
* refactor: (refactoring production code, eg. renaming a variable)
* test: (adding missing tests, refactoring tests; no production code change)
* chore: (updating grunt tasks etc; no production code change)

Thanks

**Comment by yoniaibi** [comment]
Hi, thank you for the email I forgot to mention to you that I have none of
these permissions at the time I created and I need you to give me some when
possible.

Sorry for any confusion

**Comment by yoniaibi** [comment]
Thank you for the guide on things like big fix ect and what they mean that
is super helpful!

**Comment by piotrostr** [comment]
no worries, let me know if you need anything!
